Update pkcsutil.py
When not giving a passphrase, like 59 bails out because None doesn't have a length:

```
Traceback (most recent call last):
  File "pkcsutil.py", line 59, in <module>
    if len(passphrase) == 0:
TypeError: object of type 'NoneType' has no len()
```

Setting the default to empty string fixes that.